### ISSUE TITLE
Reimport tracking result with different post processing parameter

### ISSUE THREAD

**Issue by michael-mueller-git** [michael-mueller-git/Python-Funscript-Editor#22]
Requested feature from WIZARD at eroscripts:

> Would it be possible to integrate some sort of “undo” function, where after adjusting the processing menu of the tracking generator and applying the results, to go back to that processing menu if you are not satisfied with the inputted data into the OFS ‘positions’ bar?

**Comment by michael-mueller-git** [comment]
Required Implementation:

- [x] Button in Lua plugin to trigger post processing from last raw data. At import first delete the current existing data in the range of the new data.
- [x] CLI Args in MTFG for post processing from last raw data
- [x] Always save raw data when tracking is completed
- [x] Testing

**Comment by michael-mueller-git** [comment]
available with [v0.5.1](https://github.com/michael-mueller-git/Python-Funscript-Editor/releases/tag/v0.5.1)
